#+title: todo
#+author: natan
#+STARTUP: indent
#+TODO: TODO DOING WAITING CANCELED | DONE

* DONE 1. Remove services
Remove services to get a more event oriented api.
** DONE 1.1. key-value-repository -> database
Remove the repository

New Events:
#+begin_src cpp
  gameEmitter->emit({"database/set", any})
  gameEmitter->emit({"database/get", any})
  gameEmitter->emit({"database/unset", any})
#+end_src

** DONE 1.2. log-service -> log.h
Remove the service

New events:
#+begin_src cpp
  gameEmitter->emit({"log/info", string})
#+end_src

** DONE 1.3. tile-service -> tile.cc (with static draw method) -> texture-loader.cc
Remove service and create a new texture-loader

** DONE 1.4. game-service.cc -> game.cc -> game-state.cc
** DONE 1.4. game-service.cc -> game.cc -> game-state.cc
Remove the service

New events:
#+begin_src cpp
  gameEmitter->emit({"game/state", &GameState})
#+end_src
* WAITING 2. New Functional API
** 2.1. Old API
Mainly composed using Observer Pattern and Service Pattern.
#+begin_src c++
  gameEmitter->on("game/init", [this](Event event) { onInit(); });
  gameEmitter->on("game/start", [this](Event event) { onStart(); });
  gameEmitter->on("game/restart", [this](Event event) { onRestart(); });
  gameEmitter->on("game/update", [this](Event event) { onUpdate(); });
  gameEmitter->on("game/render", [this](Event event) { onRender(); });
  gameEmitter->on("game/stop", [this](Event event) { onStop(); });
  gameEmitter->on("game/deinit", [this](Event event) { onDeinit(); });
  gameEmitter->on("game/pause", [this](Event event) { onPause(); });
  gameEmitter->on("game/resume", [this](Event event) { onResume(); });
#+end_src
Service call:
#+begin_src c++
  gameService->isPaused();
#+end_src

** 2.2. New API more functional
Create a more functional api. One function per lifecycle/event,
#+begin_src c++
  useStart([] {
    "..."
      });
#+end_src

#+begin_src c++
  useState([](State state, function setState) {
    "..."
      });
#+end_src

#+begin_src c++
  useRender([]{
    useState([](State state, function setState) {
      "..."
        });
   })
#+end_src
* DONE 3. Async pointer
** Descrition
Create a mechanism to keep pointers to instances using the event system or a dependency injection solution.

** Solution
Given classB depends on classA and that container instantiate at least classA.
At the container:
#+begin_src cpp
  ...
  AsyncPointer::register(objectOfClassA);
  ...
#+end_src
On classB:
#+begin_src cpp
  ...
  ClassA *objectOfClassA = AsyncPointer::get<ClassA>();
  ...
#+end_src
* 4. Collision basic API
** DOING 4.1. Create an abstract class to represent geometries (Rectangle, Circle...)
Class Geometry should be defined as below.
#+begin_src cpp
  struct Vector2 {
    float x;                // Vector x component
    float y;                // Vector y component
  };

  typedef struct Vector3 {
    float x;                // Vector x component
    float y;                // Vector y component
    float z;                // Vector z component
  };

  struct Point {
    struct Vector2;
  };

  struct Line {
    Vector2 point1;
    Vector2 point2;
  };

  struct Triangle {
    Vector2 point1;
    Vector2 point2;
    Vector2 point3;
  };

  struct Rectangle {
    float x;
    float y;
    float width;
    float height;
  };

  struct Circle {
    Vector2 center;
    float radius;
  };

  struct BoundingBox {
    Vector3 min;            // Minimum vertex box-corner
    Vector3 max;            // Maximum vertex box-corner
  };

  struct Sphere {
    Vector3 center;
    float radius;
  };

  struct Poly {
    Vector3 *points;
    int pointCount;
  };

  class Geometry {
    std::variant<Rectangle
                 Circle,
                 Point,
                 Triangle,
                 Poly,
                 Line,
                 BoundingBox,
                 Sphere> raw;

    bool checkCollision(const Geometry &other) const {
      if(std::holds_alternative<Rectangle>(raw) && std::holds_alternative<Rectangle>(other.raw)) {
        Rectangle rec0 = std::any_cast<Rectangle>(raw);
        Rectangle rec1 = std::any_cast<Rectangle>(other.raw);
        return CheckCollisionRecs(rec0, rec1);
      } else if(std::holds_alternative<Circle>(raw) && std::holds_alternative<Rectangle>(other.raw)) {
        Circle circ0 = std::any_cast<Circle>(raw);
        Rectangle rec1 = std::any_cast<Rectangle>(other.raw);
        return CheckCollisionRecs(circ0.center, circ0.radius, rec1);
      }
      //...
      //other ifs
      //...
    }

    void translate(const Vector2 &translation, Geometry &out) const {
      if(std::holds_alternative<Rectangle>(raw)) {
        if(!std::holds_alternative<Rectangle>(out.raw)) {
          out.raw = std::get<Rectangle>(raw);
        }
        Rectangle &rec = std::get<Rectangle>(out.raw);
        rec.x += translaion.x;
        rec.y += translaion.y;
      }
      //...
      //other ifs
      //...
    }
  }

    class GameNode2D {
      Geometry geometry;
      Geometry transformedGeometry;

      bool checkCollision(const GameNode2D &other) const {
        gemometry.translate(position, transformedGeometry);
        other.geometry.translate(other.position, other.transformedGeometry);
        return transformedGeometry.checkCollision(other.transformedGeometry);
      }
    }
#+end_src
** CANCELED 4.2. Create ways to define and scale the collision geometry
** 4.3. Debug collision borders
Create a variable to show/hide the collision shape
